# Generated by Django 4.2.5 on 2023-11-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='превью')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='превью')),
                ('description', models.TextField(verbose_name='описание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата оплаты')),
                ('summ_of_fee', models.IntegerField(verbose_name='цена')),
                ('way_of_pay', models.CharField(choices=[('cash', 'наличными'), ('bank_transfer', 'перевод на счет')], max_length=16, verbose_name='способ оплаты')),
                ('session_id', models.CharField(max_length=80, verbose_name='id сессии')),
                ('is_paid', models.BooleanField(verbose_name='поступил ли платеж')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс')),
            ],
        ),
    ]
